/**
 * galaxy-cone/loader.ts — binary fetch + decode for the 2MRS+6dFGS
 * galaxy-cone catalog.
 *
 * Binary layout (no header — pure record stream so the file size is the
 * count × 16). Little-endian. Each row is 16 bytes:
 *
 *   [ ra_rad: float32, dec_rad: float32, cz_kms: float32, K_mag: float32 ]
 *
 *   • ra_rad  — heliocentric right ascension, ICRS J2000, radians [0, 2π)
 *   • dec_rad — declination, radians [-π/2, +π/2]
 *   • cz_kms  — heliocentric recession velocity (km/s); distance = cz/H0
 *   • K_mag   — apparent 2MASS K_s magnitude (≈ 6-15 for the catalog)
 *
 * The file lives at `apps/web/public/data/galaxy-cone.bin` and is
 * generated by `scripts/bake-galaxy-cone.ts`.
 */

export type GalaxyRow = {
  /** RA in radians (ICRS J2000). */
  raRad: number;
  /** Dec in radians. */
  decRad: number;
  /** Heliocentric recession velocity, km/s. */
  czKms: number;
  /** Apparent 2MASS K_s magnitude. NaN if unknown. */
  kMag: number;
};

export type GalaxyCatalog = {
  count: number;
  /** Backing Float32Array view of length count*4 (ra, dec, cz, K). */
  raw: Float32Array;
};

/** Default public-URL path. Hosted at the apps/web origin. */
export const DEFAULT_CATALOG_URL = "/data/galaxy-cone.bin";

/**
 * Fetch the binary catalog and return a typed view. We keep one
 * contiguous Float32Array around (no row objects) so the renderer can
 * iterate without allocating; per-row access is via small accessor
 * helpers below.
 */
export async function loadGalaxyCatalog(
  url = DEFAULT_CATALOG_URL,
  signal?: AbortSignal,
): Promise<GalaxyCatalog> {
  const init: RequestInit | undefined =
    typeof signal !== "undefined" ? { signal } : undefined;
  const res = await fetch(url, init);
  if (!res.ok) {
    throw new Error(`galaxy-cone: HTTP ${res.status} fetching ${url}`);
  }
  const buf = await res.arrayBuffer();
  // 16 bytes per row — 4 × float32.
  if (buf.byteLength % 16 !== 0) {
    throw new Error(
      `galaxy-cone: malformed catalog (${buf.byteLength} bytes, not %16)`,
    );
  }
  const raw = new Float32Array(buf);
  const count = raw.length / 4;
  return { count, raw };
}

/** Read row i out of the packed buffer. */
export function rowAt(cat: GalaxyCatalog, i: number): GalaxyRow {
  const o = i * 4;
  return {
    raRad: cat.raw[o] ?? 0,
    decRad: cat.raw[o + 1] ?? 0,
    czKms: cat.raw[o + 2] ?? 0,
    kMag: cat.raw[o + 3] ?? Number.NaN,
  };
}
